# Generated by Django 3.1.7 on 2021-03-02 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
